=== Thoris/CITools/Nester/Grammar.dtd
<!ENTITY % RuleTypes "(NumberConstant|StringConstant|Literal|BooleanConstant|CharConstant|Or|Sequence|Repeater|List|Ref|Id|BinaryOperator)">
<!ELEMENT Grammar ((%RuleTypes;)+)>
<!ELEMENT NumberConstant EMPTY>
<!ELEMENT StringConstant EMPTY>
<!ELEMENT Literal EMPTY>
<!ELEMENT BooleanConstant EMPTY>
<!ELEMENT CharConstant EMPTY>
<!ELEMENT Or ((%RuleTypes;)+)>
<!ELEMENT Sequence ((%RuleTypes;)+)>
<!ELEMENT Repeater ((%RuleTypes;)+)>
<!ELEMENT List ((%RuleTypes;)+)>
<!ELEMENT Ref EMPTY>
<!ELEMENT Id EMPTY>
<!ELEMENT BinaryOperator (%RuleTypes;, %RuleTypes;)>

<!ENTITY % DefaultAttr "name CDATA #IMPLIED optional CDATA #IMPLIED kill CDATA #IMPLIED peek CDATA #IMPLIED supressed CDATA #IMPLIED">
<!ATTLIST Grammar %DefaultAttr; defaultrule CDATA #REQUIRED>
<!ATTLIST NumberConstant %DefaultAttr;>
<!ATTLIST StringConstant %DefaultAttr;>
<!ATTLIST BooleanConstant %DefaultAttr;>
<!ATTLIST CharConstant %DefaultAttr;>
<!ATTLIST Literal pattern CDATA #REQUIRED %DefaultAttr;>
<!ATTLIST Or %DefaultAttr;>
<!ATTLIST Sequence %DefaultAttr; nospace CDATA #IMPLIED>
<!ATTLIST Repeater %DefaultAttr; strict CDATA #IMPLIED>
<!ATTLIST List delimiter CDATA #IMPLIED %DefaultAttr;>
<!ATTLIST Ref rule CDATA #REQUIRED %DefaultAttr;>
<!ATTLIST Id %DefaultAttr; excluded CDATA #IMPLIED>
<!ATTLIST BinaryOperator %DefaultAttr;>

=== Thoris/CITools/Nester/CSGrammar.xml
<?xml version="1.0" encoding="utf-8" ?> 
<!DOCTYPE Grammar SYSTEM "Grammar.dtd">
<!-- C# grammar for the Nester defect inserter.
    By John Melville, MS, MD
    This file follows the official C# grammar as closely as possible.
    Only grammar inside a method or property is implemented so far
-->
<Grammar defaultrule ="TopLevel">
    <!-- this searches for methods and properties it is the top level production and is a little bit ad hoc -->
    <Or name ="TopLevel">
        <Ref rule ="MethodDecl"/>
        <Ref rule ="PropertyDecl"/>
    </Or>
	
    <Sequence name ="MethodDecl">
		<Or>
			<Sequence>
				<Or optional ="true"> 
					<Ref rule ="Type"/>
					<Literal pattern ="void"/>
				</Or>
				<Ref rule ="Identifier"/>
			</Sequence>
			<Ref rule ="Identifier"/>
		</Or>
        <Ref rule ="TypeParameterList" optional ="true"/>
        <Literal pattern ="("/>
		<Ref rule ="MethodParamList" optional ="true"/>
        <Literal pattern=")"/>
        <Sequence name ="ConstructorCall" optional="true">
            <Literal pattern =":"/>
            <Or>
                <Literal pattern="this"/>
                <Literal pattern ="base"/>
            </Or>
            <Literal pattern="("/>
            <Ref rule ="ArgumentList" optional="true"/>
            <Literal pattern=")"/>
        </Sequence>
        <Ref rule ="Block" name ="MethodBlock"/>
    </Sequence>
    <List delimiter="," name ="MethodParamList">
        <Sequence name ="MethodParam">
            <Or optional="true">
                <Literal pattern="params"/>
                <Literal pattern="ref"/>
                <Literal pattern="out"/>
            </Or>
            <Ref rule ="Type"/>
            <Ref rule ="Identifier"/>
        </Sequence>
    </List>
    
    <Sequence name = "PropertyDecl">
        <Ref rule ="Type"/>
		<List delimiter =".">
			<Or>
				<Ref rule ="Identifier"/>
				<Literal pattern ="this"/>
			</Or>
		</List>
		<Sequence optional = "true">
			<Literal pattern ="["/>
			<Ref rule ="MethodParamList" optional ="true"/>
			<Literal pattern ="]"/>
		</Sequence>
        <Literal pattern ="{"/>
        <List>
            <Or>
                <Sequence>
                    <Literal pattern ="get"/>
                    <Ref rule="Block" name ="GetBlock"/>
                </Sequence>
                <Sequence>
                    <Literal pattern ="set"/>
                    <Ref rule="Block" name ="SetBlock"/>
                </Sequence>
            </Or>
        </List>
        <Literal pattern ="}"/>
    </Sequence>
    
    <!-- Starting at section 9.2 of the csharp grammar-->
    <Or name ="Statement">
        <Ref rule = "Block"/>
        <Literal pattern =";" name ="EmptyStatement"/>
        <Ref rule ="LabelStatement"/>
        <Ref rule ="LocalVariableDeclarationStatement"/>
        <Ref rule ="IfStatement"/>
        <Ref rule ="SwitchStatement"/>
        <Ref rule ="WhileStatement"/>
        <Ref rule ="DoStatement"/>
        <Ref rule = "ForStatement"/>
        <Ref rule = "ForeachStatement"/>
        <Ref rule ="JumpStatements"/>
        <Ref rule ="TryStatement"/>
        <Ref rule ="CheckedStatement"/>
        <Ref rule ="UncheckedStatement"/>
        <Ref rule ="LockStatement"/>
        <Ref rule ="UsingStatement"/>
        <Ref rule ="UnsafeStatement"/>
        <Ref rule ="FixedStatement"/>
        <Sequence name ="ExpressionStatement"><Ref rule ="Expression"/><Literal pattern=";"/></Sequence>
    </Or>
    
    <Or name ="JumpStatements">
        <Sequence name ="BreakStatement"><Literal pattern ="break"/><Literal pattern =";"/></Sequence>
        <Sequence name ="ContinueStatement"><Literal pattern ="continue"/><Literal pattern =";"/></Sequence>
        <Ref rule ="GotoStatement"/>
        <Ref rule ="ReturnStatement"/>
        <Ref rule ="YieldStatement"/>
        <Ref rule ="ThrowStatement"/>        
    </Or>
    
    
    <Sequence name ="Block">
        <Literal pattern="{"/>
        <List name ="BlockMemberList" optional ="true">
            <Ref name ="BlockMember" rule ="Statement"/>
        </List>
        <Literal pattern ="}"/>
    </Sequence>
  
    <Sequence name ="LabelStatement">
        <Ref rule ="Identifier" name ="Label"/>
        <Literal pattern =":"/>
        <Ref rule ="Statement" name="LabeledStatement"/>
    </Sequence>
    
    <Sequence name ="LocalVariableDeclarationStatement">
        <Ref rule ="LocalVariableDeclaration"/>
        <Literal pattern =";"/>
    </Sequence>
    
    <Sequence name="LocalVariableDeclaration">
        <Literal pattern ="const" optional ="true" name ="ConstToken"/>
        <Ref rule ="Type" name ="LocalVariableDeclType"/>
        <List delimiter ="," name ="LocalVariableDeclaratorList">
            <Sequence name ="LocalVariableDeclarator">
                <Ref rule ="Identifier" name ="DeclLocalVariable"/>
                <Sequence  optional ="true">
                    <Literal pattern = "="/>
                    <Ref rule ="LocalVariableInitalizer"/>
                </Sequence>
            </Sequence>
        </List>
    </Sequence>

    <Or name ="LocalVariableInitalizer">
        <Literal pattern="null"/> <!-- included so that the coverage analyzer doesn't mutate type x = null-->
        <Ref name="InitalizeExpression" rule ="Expression"/>
        <Ref name="InitalizeExpression" rule ="ArrayInitalizer"/>
        <Ref rule ="StackAllocInitalizer"/>
    </Or>
    
    <Sequence name="StackAllocInitalizer">
        <Literal pattern ="stackalloc"/>
        <Ref rule ="Type" name ="StackAllocType"/>
        <Literal pattern ="["/>
        <Ref rule ="Expression" name ="StackAllocExpression"/>
        <Literal pattern ="]"/>
    </Sequence>
        
    <Sequence name ="IfStatement">
        <Literal pattern ="if"/>
        <Literal pattern ="("/>
        <Ref rule ="Expression" name ="IfCondition"/>
        <Literal pattern =")"/>
        <Ref rule ="Statement" name ="IfTrueBranch"/>
        <Sequence name ="ElseBlock" optional ="true">
            <Literal pattern ="else"/>
            <Ref rule ="Statement" name ="IfElseBranch"/>
        </Sequence>
    </Sequence>
    
    <Sequence name ="SwitchStatement">
        <Literal pattern ="switch"/>
        <Literal pattern ="("/>
        <Ref rule ="Expression" name ="SwitchExpression"/>
        <Literal pattern =")"/>
        <Literal pattern ="{"/>
        <List optional ="true">
            <Sequence>
                <Or>
                    <Literal pattern="default"/>
                    <Sequence>
                        <Literal pattern ="case"/> 
                        <Ref rule ="Expression" name ="CaseExpression" supressed="true"/>
                    </Sequence>
                </Or>
                <Literal pattern =":"/>
                <List optional = "true" name ="CaseStatementList">
                    <Ref rule ="Statement" name ="CaseStatement"/>
                </List>
            </Sequence>
        </List>
        <Literal pattern ="}"/>
    </Sequence>
    
    <Sequence name="WhileStatement">
        <Literal pattern ="while"/>
        <Literal pattern ="("/>
        <Ref rule ="Expression" name ="WhileCondition"/>
        <Literal pattern =")"/>
        <Ref rule="Statement" name ="WhileLoopStatement"/>
    </Sequence>
    
    <Sequence name="DoStatement">
        <Literal pattern ="do"/>
        <Ref rule="Statement" name ="DoLoopStatement"/>
        <Literal pattern ="while"/>
        <Literal pattern ="("/>
        <Ref rule ="Expression" name ="DoCondition"/>
        <Literal pattern =")"/>
        <Literal pattern =";"/>
    </Sequence>
    
    <Sequence name ="ForStatement">
        <Literal pattern ="for"/>
        <Literal pattern ="("/>
        <List delimiter ="," optional ="true">
		  <Or name ="ForInitalizer">
	          <Ref rule ="Expression"/>
			  <Ref rule ="LocalVariableDeclaration"/>
		  </Or>
        </List>
        <Literal pattern=";"/>
        <Ref name ="ForCondition" rule ="Expression" optional ="true"/>
        <Literal pattern=";"/>
        <Ref name="ForIterator" rule ="Expression" optional ="true"/>
        <Literal pattern =")"/>
        <Ref name ="ForLoopStatement" rule ="Block"/>
    </Sequence>
    
    <Sequence name ="ForeachStatement">
        <Literal pattern ="foreach"/>
        <Literal pattern ="("/>
        <Ref rule ="Type" name ="ForeachElementType"/>
        <Ref rule ="Identifier" name="ForeachElement"/>
        <Literal pattern ="in"/>
        <Ref rule="Expression" name ="ForeachCollection"/>
        <Literal pattern =")"/>
        <Ref rule ="Statement" name ="ForeachLoopStatement"/>
    </Sequence>
    
    <Sequence name = "GotoStatement">
        <Literal pattern ="goto"/>
        <Or>
          <Ref rule ="Identifier" name ="GotoLabel"/>
          <Sequence><Literal pattern ="case"/><Ref rule ="Expression" name ="GotoCaseExpression"/></Sequence>
          <Literal pattern ="default"/>
        </Or>
        <Literal pattern =";"/>
    </Sequence>
    
    <Sequence name ="ReturnStatement">
        <Literal pattern ="return"/>
        <Ref rule ="Expression" name ="ReturnedValue" optional ="true"/>
        <Literal pattern =";"/>
    </Sequence>
    <Sequence name ="YieldStatement">
        <Literal pattern="yield"/>
        <Or>
            <Sequence>
                <Literal pattern="return"/>
                <Ref rule="Expression" name="YieldedValue"/>
            </Sequence>
            <Literal pattern="break"/>
        </Or>
        <Literal pattern=";"/>
    </Sequence>
    <Sequence name ="ThrowStatement">
        <Literal pattern ="throw"/>
        <Ref rule ="Expression" name ="ThrownValue" optional ="true"/>
        <Literal pattern =";"/>
    </Sequence>
    
    <Sequence name ="TryStatement">
        <Literal pattern ="try"/>
        <Ref rule ="Block" name ="TryProtectedBlock"/>
        <List>
            <Or>
                <Sequence>
                    <Literal pattern="catch"/>
